# Generated by Django 3.2.21 on 2023-09-06 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlignmentContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shortname', models.CharField(max_length=5)),
                ('full_description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('full_description', models.CharField(max_length=1000)),
                ('feature', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=200)),
                ('faith', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=4)),
                ('notes', models.CharField(max_length=1000)),
                ('backstory', models.CharField(max_length=10000)),
                ('allies', models.CharField(max_length=200)),
                ('enemies', models.CharField(max_length=200)),
                ('factions_and_orgs', models.CharField(max_length=200)),
                ('alignment', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='CharacterAlignment', to='charmodels.alignmentcontenttable')),
                ('background', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='CharacterBackground', to='charmodels.backgroundcontenttable')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSavingThrows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SavingThrowsGoverningAttribute', to='charmodels.attributecontenttable')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SavingThrowsCharacter', to='charmodels.characterdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ClassContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('full_description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('full_description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='RaceContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('full_description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shortname', models.CharField(max_length=5)),
                ('full_description', models.CharField(max_length=400)),
                ('attribute', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='SkillsGoverningAttribute', to='charmodels.attributecontenttable')),
            ],
        ),
        migrations.CreateModel(
            name='SpellsContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('full_description', models.CharField(max_length=1000)),
                ('spell_reqs', models.IntegerField(choices=[(0, ''), (1, 'Verbal'), (2, 'Somatic'), (3, 'Verbal and Somatic'), (4, 'Material'), (5, 'Verbal and Material'), (6, 'Somatic and Material'), (7, 'Verbal, Somatic and Material')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubClassContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('full_description', models.CharField(max_length=400)),
                ('parent_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubclassParentClass', to='charmodels.classcontenttable')),
            ],
        ),
        migrations.CreateModel(
            name='SubRaceContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('full_description', models.CharField(max_length=400)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubraceParentRace', to='charmodels.racecontenttable')),
            ],
        ),
        migrations.CreateModel(
            name='ToolContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('full_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SubraceToSkillProficiencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_proficiency_granted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubraceSkillGranted', to='charmodels.skillscontenttable')),
                ('subrace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SkillprofsSubrace', to='charmodels.subracecontenttable')),
            ],
        ),
        migrations.CreateModel(
            name='SubraceTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subrace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ToolsSubrace', to='charmodels.subracecontenttable')),
                ('tool_proficiency_granted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubraceToolProficiencyGranted', to='charmodels.toolcontenttable')),
            ],
        ),
        migrations.CreateModel(
            name='SubraceSpells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spells_granted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubraceSpellsGranted', to='charmodels.spellscontenttable')),
                ('subrace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SpellsSubrace', to='charmodels.subracecontenttable')),
            ],
        ),
        migrations.CreateModel(
            name='SubraceLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_granted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubraceLanguageGranted', to='charmodels.languagecontenttable')),
                ('subrace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LanguagesSubrace', to='charmodels.subracecontenttable')),
            ],
        ),
        migrations.CreateModel(
            name='SubclassSpellsGranted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spells_granted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubclassSpellsGranted', to='charmodels.spellscontenttable')),
                ('subclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SpellsSubclass', to='charmodels.subclasscontenttable')),
            ],
        ),
        migrations.CreateModel(
            name='SubclassSkillProficiencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_proficiency_granted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubclassSkillGranted', to='charmodels.skillscontenttable')),
                ('subclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SkillprofsSubclass', to='charmodels.subclasscontenttable')),
            ],
        ),
        migrations.CreateModel(
            name='SubclassLanguageProficiencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_granted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubclassLanguageGranted', to='charmodels.languagecontenttable')),
                ('subclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LanguagesSubclass', to='charmodels.subclasscontenttable')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSpellsGranted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SpellsClass', to='charmodels.subracecontenttable')),
                ('spells_granted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClassSpellsGranted', to='charmodels.spellscontenttable')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSkillProficiencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SkillProfsClass', to='charmodels.subracecontenttable')),
                ('skill_proficiency_granted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClassSkillGranted', to='charmodels.skillscontenttable')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSavingThrows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SavingThrowsClass', to='charmodels.subracecontenttable')),
                ('saving_throws_granted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClassSavingThrowsGranted', to='charmodels.charactersavingthrows')),
            ],
        ),
        migrations.CreateModel(
            name='ClassLanguageProficiencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LanguagesClass', to='charmodels.subracecontenttable')),
                ('language_granted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClassLanguageGranted', to='charmodels.languagecontenttable')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSpells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SpellsCharacter', to='charmodels.characterdetails')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CharacterSpells', to='charmodels.spellscontenttable')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSkillProficiencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.IntegerField(choices=[(0, 'Proficient'), (1, 'Expertise'), (2, 'Half-Proficiency (Bard)')])),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SkillsCharacter', to='charmodels.characterdetails')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SkillsSkill', to='charmodels.skillscontenttable')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LevelsCharacter', to='charmodels.characterdetails')),
                ('subclass', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='LevelsSubclass', to='charmodels.subclasscontenttable')),
            ],
        ),
        migrations.AddField(
            model_name='characterdetails',
            name='languages',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='CharacterLanguages', to='charmodels.languagecontenttable'),
        ),
        migrations.AddField(
            model_name='characterdetails',
            name='race',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='CharacterRace', to='charmodels.racecontenttable'),
        ),
        migrations.CreateModel(
            name='CharacterAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AttributesAttribute', to='charmodels.attributecontenttable')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AttributesCharacter', to='charmodels.characterdetails')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundToolProficiencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ToolsBackground', to='charmodels.backgroundcontenttable')),
                ('tool_proficiency_granted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BackgroundToolProficiencyGranted', to='charmodels.toolcontenttable')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundSkillProficiencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SkillprofsBackground', to='charmodels.backgroundcontenttable')),
                ('skill_proficiency_granted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backgroundSkillGranted', to='charmodels.skillscontenttable')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundLanguageProficiencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LanguagesBackground', to='charmodels.backgroundcontenttable')),
                ('language_granted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BackgroundLanguageGranted', to='charmodels.languagecontenttable')),
            ],
        ),
    ]
