# Generated by Django 3.2.21 on 2023-09-06 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charmodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterdetails',
            name='race',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='CharacterSubrace', to='charmodels.subracecontenttable'),
        ),
        migrations.AlterField(
            model_name='subracecontenttable',
            name='race',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='SubraceParentRace', to='charmodels.racecontenttable'),
        ),
    ]
