# Generated by Django 3.2.21 on 2023-09-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charmodels', '0003_auto_20230906_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterdetails',
            name='armor_class',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='characterdetails',
            name='hit_points',
            field=models.IntegerField(default=12),
        ),
    ]
