# Generated by Django 3.2.21 on 2023-09-06 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charmodels', '0004_auto_20230906_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterdetails',
            name='languages',
        ),
        migrations.CreateModel(
            name='CharacterLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LanguagesCharacter', to='charmodels.characterdetails')),
                ('language_granted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CharacterLanguageGranted', to='charmodels.languagecontenttable')),
            ],
        ),
    ]
