# Generated by Django 3.2.21 on 2023-09-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charmodels', '0007_auto_20230906_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alignmentcontenttable',
            options={'verbose_name': 'Alignment'},
        ),
        migrations.AlterModelOptions(
            name='attributecontenttable',
            options={'verbose_name': 'Attribute'},
        ),
        migrations.AlterModelOptions(
            name='backgroundcontenttable',
            options={'verbose_name': 'Background'},
        ),
        migrations.AlterModelOptions(
            name='backgroundlanguageproficiencies',
            options={'verbose_name': 'Background Granted Language'},
        ),
        migrations.AlterModelOptions(
            name='backgroundskillproficiencies',
            options={'verbose_name': 'Background Granted Skill'},
        ),
        migrations.AlterModelOptions(
            name='backgroundtoolproficiencies',
            options={'verbose_name': 'Background Granted Tool'},
        ),
        migrations.AlterModelOptions(
            name='characterattributes',
            options={'verbose_name': 'Character Attribute'},
        ),
        migrations.AlterModelOptions(
            name='characterdetails',
            options={'verbose_name': 'Character'},
        ),
        migrations.AlterModelOptions(
            name='characterlanguages',
            options={'verbose_name': 'Character Language'},
        ),
        migrations.AlterModelOptions(
            name='characterlevels',
            options={'verbose_name': 'Character Level'},
        ),
        migrations.AlterModelOptions(
            name='charactersavingthrows',
            options={'verbose_name': 'Character Saving Throw'},
        ),
        migrations.AlterModelOptions(
            name='characterskillproficiencies',
            options={'verbose_name': 'Character Skill'},
        ),
        migrations.AlterModelOptions(
            name='characterspells',
            options={'verbose_name': 'Character Spell'},
        ),
        migrations.AlterModelOptions(
            name='classcontenttable',
            options={'verbose_name': 'Class Choice'},
        ),
        migrations.AlterModelOptions(
            name='classlanguageproficiencies',
            options={'verbose_name': 'Class Granted Language'},
        ),
        migrations.AlterModelOptions(
            name='classsavingthrows',
            options={'verbose_name': 'Class Granted Saving Throw'},
        ),
        migrations.AlterModelOptions(
            name='classskillproficiencies',
            options={'verbose_name': 'Class Granted Skill'},
        ),
        migrations.AlterModelOptions(
            name='classspellsgranted',
            options={'verbose_name': 'Class Granted Spell'},
        ),
        migrations.AlterModelOptions(
            name='languagecontenttable',
            options={'verbose_name': 'Language'},
        ),
        migrations.AlterModelOptions(
            name='racecontenttable',
            options={'verbose_name': 'Race'},
        ),
        migrations.AlterModelOptions(
            name='skillscontenttable',
            options={'verbose_name': 'Skill'},
        ),
        migrations.AlterModelOptions(
            name='spellscontenttable',
            options={'verbose_name': 'Spell'},
        ),
        migrations.AlterModelOptions(
            name='subclasscontenttable',
            options={'verbose_name': 'Subclass Choice'},
        ),
        migrations.AlterModelOptions(
            name='subclasslanguageproficiencies',
            options={'verbose_name': 'Subclass Granted Language'},
        ),
        migrations.AlterModelOptions(
            name='subclassskillproficiencies',
            options={'verbose_name': 'Subclass Granted Skill'},
        ),
        migrations.AlterModelOptions(
            name='subclassspellsgranted',
            options={'verbose_name': 'Subclass Granted Spell'},
        ),
        migrations.AlterModelOptions(
            name='subracecontenttable',
            options={'verbose_name': 'Subrace'},
        ),
        migrations.AlterModelOptions(
            name='subracelanguages',
            options={'verbose_name': 'Subrace Granted Language'},
        ),
        migrations.AlterModelOptions(
            name='subracespells',
            options={'verbose_name': 'Subrace Granted Spell'},
        ),
        migrations.AlterModelOptions(
            name='subracetools',
            options={'verbose_name': 'Subrace Granted Tool'},
        ),
        migrations.AlterModelOptions(
            name='subracetoskillproficiencies',
            options={'verbose_name': 'Subrace Granted Skill'},
        ),
        migrations.AlterModelOptions(
            name='toolcontenttable',
            options={'verbose_name': 'Tool'},
        ),
        migrations.AlterField(
            model_name='backgroundcontenttable',
            name='feature',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='backgroundcontenttable',
            name='full_description',
            field=models.CharField(max_length=3000),
        ),
    ]
