# Generated by Django 3.2.21 on 2023-09-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charmodels', '0008_auto_20230906_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alignmentcontenttable',
            name='full_description',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='backgroundcontenttable',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='classcontenttable',
            name='full_description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='classcontenttable',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='languagecontenttable',
            name='full_description',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='languagecontenttable',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='racecontenttable',
            name='full_description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='racecontenttable',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skillscontenttable',
            name='full_description',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='spellscontenttable',
            name='full_description',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='subclasscontenttable',
            name='full_description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='subclasscontenttable',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subracecontenttable',
            name='full_description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='subracecontenttable',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='toolcontenttable',
            name='full_description',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='toolcontenttable',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
