# Generated by Django 3.2.21 on 2023-09-07 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charmodels', '0012_auto_20230907_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsavingthrows',
            name='saving_throws_granted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClassSavingThrowsGranted', to='charmodels.attributecontenttable'),
        ),
    ]
