# Generated by Django 3.2.21 on 2023-09-08 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charmodels', '0013_alter_classsavingthrows_saving_throws_granted'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterdetails',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='racecontenttable',
            name='features',
            field=models.TextField(default='I am blank'),
        ),
        migrations.AlterField(
            model_name='characterdetails',
            name='allies',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='characterdetails',
            name='backstory',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='characterdetails',
            name='enemies',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='characterdetails',
            name='factions_and_orgs',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='characterdetails',
            name='notes',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
