# Generated by Django 3.2.21 on 2023-09-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charmodels', '0014_auto_20230908_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcontenttable',
            name='features',
            field=models.TextField(default='I am blank'),
        ),
        migrations.AddField(
            model_name='subclasscontenttable',
            name='features',
            field=models.TextField(default='I am blank right now'),
        ),
        migrations.AddField(
            model_name='subracecontenttable',
            name='features',
            field=models.TextField(default='I am currently blank'),
        ),
        migrations.AlterField(
            model_name='alignmentcontenttable',
            name='full_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='attributecontenttable',
            name='full_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='backgroundcontenttable',
            name='feature',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='backgroundcontenttable',
            name='full_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='characterdetails',
            name='allies',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='characterdetails',
            name='backstory',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='characterdetails',
            name='enemies',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='characterdetails',
            name='factions_and_orgs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='characterdetails',
            name='faith',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='characterdetails',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='classcontenttable',
            name='full_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='instrumentcontenttable',
            name='full_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='languagecontenttable',
            name='full_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='racecontenttable',
            name='full_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='skillscontenttable',
            name='full_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='spellscontenttable',
            name='full_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subclasscontenttable',
            name='full_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subracecontenttable',
            name='full_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='toolcontenttable',
            name='full_description',
            field=models.TextField(),
        ),
    ]
