# Generated by Django 3.2.21 on 2023-09-08 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charmodels', '0015_auto_20230908_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterdetails',
            old_name='race',
            new_name='subrace',
        ),
        migrations.AddField(
            model_name='backgroundcontenttable',
            name='skill_proficiency_1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='BackgroundSkillGranted1', to='charmodels.skillscontenttable'),
        ),
        migrations.AddField(
            model_name='backgroundcontenttable',
            name='skill_proficiency_2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='BackgroundSkillGranted2', to='charmodels.skillscontenttable'),
        ),
        migrations.AddField(
            model_name='classcontenttable',
            name='saving_throw_1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='SavingThrow1', to='charmodels.attributecontenttable'),
        ),
        migrations.AddField(
            model_name='classcontenttable',
            name='saving_throw_2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='SavingThrow2', to='charmodels.attributecontenttable'),
        ),
        migrations.DeleteModel(
            name='ClassSavingThrows',
        ),
    ]
